# Generated by Django 4.2.5 on 2023-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pom_run_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pom_create_date', models.DateTimeField(verbose_name='创建日期')),
                ('pom_scan_platform', models.CharField(choices=[('baidu', '百度'), ('sogou', '搜狗'), ('haoso', '好搜'), ('bing', '必应'), ('weixin', '微信公众号'), ('tieba', '贴吧'), ('weibo', '微博'), ('zhihu', '知乎')], max_length=10, verbose_name='扫描平台')),
                ('pom_scan_page_num', models.SmallIntegerField(choices=[(3, '3'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (50, '50'), (100, '100')], verbose_name='检测页数')),
                ('pom_scan_keywords', models.CharField(max_length=3000, verbose_name='检索关键词')),
                ('pom_headless', models.CharField(max_length=4, verbose_name='无头模式')),
                ('pom_stop_load_pic', models.CharField(max_length=4, verbose_name='禁止加载图片')),
                ('pom_proxy', models.CharField(max_length=4, verbose_name='使用代理')),
                ('pom_ua', models.CharField(max_length=4, verbose_name='动态UA')),
                ('pom_login_pattern', models.CharField(max_length=4, verbose_name='登录模式')),
                ('pom_proxy_api', models.CharField(blank=True, max_length=300, null=True, verbose_name='PROXY API')),
                ('pom_cookies', models.CharField(blank=True, max_length=300, null=True, verbose_name='COOKIES')),
                ('pom_token', models.CharField(blank=True, max_length=300, null=True, verbose_name='TOKEN')),
                ('pom_username', models.CharField(blank=True, max_length=16, null=True, verbose_name='用户名')),
                ('pom_password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
            ],
        ),
    ]
