# Generated by Django 4.2.5 on 2023-10-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tanji', '0002_tanji_customer_export'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pom_run_config',
        ),
    ]
