# Generated by Django 4.2.5 on 2023-10-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tanji', '0003_delete_pom_run_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tanji_customer_export',
            new_name='customer_export',
        ),
    ]
