# Generated by Django 4.2.5 on 2023-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_allen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tanji_customer_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('company', models.CharField(max_length=50, verbose_name='公司名称')),
                ('customer', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('tel_status', models.CharField(max_length=15, verbose_name='电话状态')),
                ('tel_result', models.CharField(max_length=15, verbose_name='拨号结果')),
                ('tel_longtime', models.CharField(max_length=10, verbose_name='通话时常')),
            ],
        ),
    ]
