# Generated by Django 4.2.5 on 2023-10-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pom_run_config',
            new_name='run_settings',
        ),
    ]
